### ISSUE TITLE
yamlbeans:1.13 android sdk 23 EmitterException

### ISSUE THREAD

**Issue by EnterTG** [EsotericSoftware/yamlbeans#106]
```
            YamlWriter reader = new YamlWriter(new FileWriter(configDir));
            System.out.println("Saving configs");
            for (ClientConfig cc : clientConfigList)
                cc.save(reader);
            reader.close();`
```

```
03-05 14:24:55.866 5784-5784/com.example.windskull.testaplication W/System.err: com.esotericsoftware.yamlbeans.YamlException
03-05 14:24:55.866 5784-5784/com.example.windskull.testaplication W/System.err:     at com.esotericsoftware.yamlbeans.YamlWriter.close(YamlWriter.java:130)
03-05 14:24:55.866 5784-5784/com.example.windskull.testaplication W/System.err:     at com.example.windskull.praca_inz_android.Configs.GlobalConfig.save(GlobalConfig.java:112)
03-05 14:24:55.866 5784-5784/com.example.windskull.testaplication W/System.err:     at com.example.windskull.praca_inz_android.Activity.MainActivity.onStop(MainActivity.java:118)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1288)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at android.app.Activity.performStop(Activity.java:6534)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3535)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3588)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at android.app.ActivityThread.access$1200(ActivityThread.java:165)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at android.os.Looper.loop(Looper.java:150)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5621)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err: Caused by: com.esotericsoftware.yamlbeans.emitter.EmitterException: Expected 'stream start' but found: <stream end>
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at com.esotericsoftware.yamlbeans.emitter.Emitter$1.expect(Emitter.java:135)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at com.esotericsoftware.yamlbeans.emitter.Emitter.emit(Emitter.java:87)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err:     at com.esotericsoftware.yamlbeans.YamlWriter.close(YamlWriter.java:127)
03-05 14:24:55.867 5784-5784/com.example.windskull.testaplication W/System.err: 	... 14 more
```

**Comment by NathanSweet** [comment]
```
Expected 'stream start' but found: <stream end>
```
I assume your input data (which is not shown) is bad.
