### ISSUE TITLE
Class tags containing '_' won't deserialize.

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/yamlbeans#12]
_From [jim.ferr...@gmail.com](https://code.google.com/u/106187084600841482336/) on March 12, 2011 17:11:47_

To reproduce the problem?
1. Create a Bean class with an embedded '_' in the name, eg com.example.yaml.Foo_Bar
2. Serialize an instance of this class to YAML.
3. Deserialize the YAML back to an instance.

Alternatively you can configure a class tag with the _:

```
config.setClassTag("Foo_Bar", Station.class);
```

I expect to get a deserialized Bean (or an error message about using '_'), but see a stack trace from Tokenizer instead:

java.lang.RuntimeException: Couldn't deserialize DTO from YAML String: Error tokenizing YAML.
    at com.mot.tod.dto.utils.YAMLBeansSerializer.fromYAML(YAMLBeansSerializer.java:94)
    at com.mot.tod.dto.utils.YAMLBeansSerializer.deepCopy(YAMLBeansSerializer.java:130)
    at com.mot.tod.dto.DTOTest.testDTO(DTOTest.java:3032)
    at com.mot.tod.dto.DTOTest.testLineupMap_Station(DTOTest.java:2662)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:73)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:46)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
    at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:45)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
Caused by: com.esotericsoftware.yamlbeans.YamlException: Error tokenizing YAML.
    at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:110)
    at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:91)
    at com.mot.tod.dto.utils.YAMLBeansSerializer.fromYAML(YAMLBeansSerializer.java:90)
    ... 27 more
Caused by: com.esotericsoftware.yamlbeans.tokenizer.Tokenizer$TokenizerException: Line 0, column 4: While scanning a tag, expected ' ' but found: '_' (95)
    at com.esotericsoftware.yamlbeans.tokenizer.Tokenizer.scanTag(Tokenizer.java:705)
    at com.esotericsoftware.yamlbeans.tokenizer.Tokenizer.fetchTag(Tokenizer.java:486)
    at com.esotericsoftware.yamlbeans.tokenizer.Tokenizer.fetchMoreTokens(Tokenizer.java:306)
    at com.esotericsoftware.yamlbeans.tokenizer.Tokenizer.peekNextToken(Tokenizer.java:122)
    at com.esotericsoftware.yamlbeans.tokenizer.Tokenizer.peekNextTokenType(Tokenizer.java:127)
    at com.esotericsoftware.yamlbeans.parser.Parser$4.produce(Parser.java:133)
    at com.esotericsoftware.yamlbeans.parser.Parser.getNextEvent(Parser.java:82)
    at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:101)
    ... 29 more

<b>What version of the product are you using? On what operating system?</b>
&#13;
1.0.6 on Windows XP&#13;
&#13;
&#13;
<b>Please provide any additional information below.</b>
&#13;

_Original issue: http://code.google.com/p/yamlbeans/issues/detail?id=12_

**Comment by HyperPlay** [comment]
Bump, this still occurs.

**Comment by ams-tschoening** [comment]
This should be fixed now: https://github.com/EsotericSoftware/yamlbeans/issues/68

**Comment by ams-tschoening** [comment]
I've ran into that issue with 1.13 yesterday and updating to 1.15 fixed it. So no guessing anymore in contrast to my former comment. :-)
