### ISSUE TITLE
How to read and write recursive objects

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/yamlbeans#9]
_From [py4fun@gmail.com](https://code.google.com/u/py4fun@gmail.com/) on January 28, 2011 18:23:32_

I have an Employee class with references to other Employees. There are 'manager' and 'deputy' properties (among many others). Unfortunately it is very common that a manager and his deputy refer to each other. It makes a circular relationship.
Currently YamlBeans fails with a StackOverflowException when I try to write such objects. Reading does not work either. (When I write anchors and aliases manually)
How should I read and write recursive structures ?

_Original issue: http://code.google.com/p/yamlbeans/issues/detail?id=9_

**Comment by Mr14huashao** [comment]
### Local simulation:
**`Employee.class`**
```java
public class Employee {

	private String name;

	private Employee manager;

	private Employee deputy;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Employee getManager() {
		return manager;
	}

	public void setManager(Employee manager) {
		this.manager = manager;
	}

	public Employee getDeputy() {
		return deputy;
	}

	public void setDeputy(Employee deputy) {
		this.deputy = deputy;
	}

	@Override
	public String toString() {
		return "Employee [name=" + name + ", manager=" + manager + ", deputy=" + deputy + "]";
	}
}

```
**Test code:**
```java
@Test
public void test002() throws YamlException {
	Employee employee = new Employee();
	employee.setName("Bill");
	
	Employee manager = new Employee();
	manager.setName("Jack");
	Employee deputy = new Employee();
	deputy.setName("Andi");
	manager.setDeputy(deputy);
	deputy.setManager(manager);
	
	employee.setManager(manager);
	employee.setDeputy(deputy);
	
	Writer sw = new StringWriter();
	YamlWriter writer = new YamlWriter(sw);
	
	writer.write(employee);
	writer.close();
	String yaml = sw.toString();
	System.out.println("1.\n" + yaml);

	YamlReader yamlReader = new YamlReader(yaml);
	Employee object = yamlReader.read(Employee.class);
	System.out.println("2.\n" + object.getManager().getDeputy().getName());
	System.out.println("3.\n" + object.getManager());
}
```
**Console output:**
```
1.
!com.esotericsoftware.yamlbeans.issue.issue9.Employee
name: Bill
deputy: &1
   name: Andi
   manager: &2
      name: Jack
      deputy: *1
manager: *2

2.
Andi

```
**Test case execution exception, exception stack information:**
```java
java.lang.StackOverflowError
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:449)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at java.lang.StringBuilder.<init>(StringBuilder.java:113)
	at com.esotericsoftware.yamlbeans.issue.issue9.Employee.toString(Employee.java:37)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.esotericsoftware.yamlbeans.issue.issue9.Employee.toString(Employee.java:37)
	at java.lang.String.valueOf(String.java:2994)
...
```

@NathanSweet 
In this case, serialization and deserialization are not abnormal.
`java.lang.StackOverflowError` exception, caused by the `Employee.toString()` method.

**Comment by NathanSweet** [comment]
Thanks for looking into it!
