### ISSUE TITLE
ymalReader can not parse java.math.BigDecimal

### ISSUE THREAD

**Issue by cyg056** [EsotericSoftware/yamlbeans#99]
com.esotericsoftware.yamlbeans.YamlReader$YamlReaderException: Line 12, column 43: Expected data for a java.math.BigDecimal field but found: scalar
	at com.esotericsoftware.yamlbeans.YamlReader.readValueInternal(YamlReader.java:437)
	at com.esotericsoftware.yamlbeans.YamlReader.readValue(YamlReader.java:138)
	at com.esotericsoftware.yamlbeans.YamlReader.readValueInternal(YamlReader.java:379)
	at com.esotericsoftware.yamlbeans.YamlReader.readValue(YamlReader.java:138)
	at com.esotericsoftware.yamlbeans.YamlReader.readValueInternal(YamlReader.java:355)

**Comment by NathanSweet** [comment]
YamlBeans doesn't try to write all known classes. It uses reflection to write fields/bean properties. When this is not sufficient, you need to write your own serializer. See YamlConfig `setScalarSerializer`.
